### ISSUE TITLE
Create Volunteer Tab Documentation

### ISSUE THREAD

**Issue by JaredDanielJones** [Some-Apps/ShelterPartner#169]
This would include the following documents

- [ ]  Volunteer View
- [ ]  Animal Card
- [ ]  Details View
- [ ]  Add Note View
- [ ]  QR Code Option
- [ ]  Give Feedback Button
- [ ]  Report Problem Button

And anything else that should be written down.

**Comment by kateoconn1** [comment]
Hi, I'd like to take on this issue!

**Comment by JaredDanielJones** [comment]
Sounds good!

**Comment by JaredDanielJones** [comment]
@all-contributors please add @kateoconn1  for doc
