### ISSUE TITLE
Create Settings Tab Documentation

### ISSUE THREAD

**Issue by JaredDanielJones** [Some-Apps/ShelterPartner#171]
This would include the following documents

- [ ]  Settings View
- [ ]  Account Details Section
- [ ]  Shelter Settings (should be it's own directory/folder containing a document for each setting inside)
- [ ]  Device Settings (should be it's own directory/folder containing a document for each setting inside)
- [ ]  Account Section
- [ ]  About Section

And anything else that should be written down.

**Comment by rhjones777** [comment]
I'll start working on this one. You can assign it to me.

**Comment by JaredDanielJones** [comment]
awesome thank you!
